services:
  postgres:
    image: postgres:16-alpine
    container_name: daumgrito-postgres
    environment:
      POSTGRES_USER: daumgrito
      POSTGRES_PASSWORD: daumgrito
      POSTGRES_DB: daumgrito
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
